version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: devbridge-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: global_devbridge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: devbridge-backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/global_devbridge?schema=public
      - JWT_SECRET=super_secret_docker_key
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm start"

  frontend:
    build: ./frontend
    container_name: devbridge-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
